# Based on
#   https://gist.github.com/daicham/5ac8461b8b49385244aa0977638c3420
#   https://gitlab.com/gitlab-org/gitlab-ce/blob/7d1216016cfc64e35955249e39c46615e2dbdf93/lib/gitlab/ci/templates/Gradle.gitlab-ci.yml
#image: java:8-jdk
#image: gradle:5.2.1-jdk8
image: docker.io/manics/omero-build-gradle

variables:
  # Clone submodules
  GIT_SUBMODULE_STRATEGY: recursive
  GRADLE_OPTS: "-Dorg.gradle.daemon=false"

stages:
  - build
  - test
  - package

before_script:
#  - echo `pwd` # debug
#  - echo "$CI_BUILD_NAME, $CI_BUILD_REF_NAME $CI_BUILD_STAGE" # debug
  - export GRADLE_USER_HOME=`pwd`/.gradle

cache:
  key: "$CI_COMMIT_REF_NAME"
#  policy: push
  paths:
    # - .gradle/wrapper
    # - .gradle/caches
    - .gradle
    - build
    - .m2

build:
  stage: build
  script:
    - ./gitlab/mvn-repository.sh
    - git clone --recursive git://github.com/manics/omero-gradle-plugins --branch m4+gitlab tmp/omero-gradle-plugins
    - cd tmp/omero-gradle-plugins && gradle publishToMavenLocal && cd ../..
    - gradle publishToMavenLocal -x test -x javadoc
  artifacts:
    paths:
      - omero-*/build/libs/*.jar
    expire_in: 1 week
  # only:
  #   - master

test:
  stage: test
  script:
    # - ./gradlew test
    - echo TODO

package:
  stage: package
  script:
    - ./gradlew publish -x test -x javadoc

after_script:
  - echo "End CI"
